### ISSUE TITLE
Percentages

### ISSUE THREAD

**Issue by adantart** [andig/php-shunting-yard#7]
I'm looking to enhance the parser allowing the % symbol, not as MOD, but a percentage of the previous number.

I like how Google handles this:
5 + 25%   becomes   5 + (5 * 25 / 100)
5 * 25%   becomes   5 * 25 / 100

To avoid collision with the "mod" operator, that has two numbers (one in the left and one in the right) , I thought about pre-parsing the string:

```
		$string_m = preg_replace("/\s/", "", $term);
		preg_match("/([0-9]*)([^0-9])([0-9]*)\%([^0-9])/", $string_m . " ", $m);
		if (isSet($m[2])) { // Operand + or *
			if ($m[2] == "+") {
				$string = str_replace($m[3]."%", "(".$m[1]."*".$m[3]."/100)", $string_m);
			}
			if ($m[2] == "*") {
				$string = str_replace($m[3]."%", $m[3]."/100", $string_m);
			}
		}
```

With this:
12 + 150 * 15% + 3       becomes      12 + 150 * 15/100 + 3 
12 + 150 + 15% + 3       becomes      12 + 150 + (150*15/100) + 3 

So then the Parser can continue with no problems ;-)

Would you like to include in your parser ?

**Comment by andig** [comment]
To be frank, I don‘t see much value in doing that. Multiplying by 1.25 will yield the same result without an additional operator.

**Comment by adantart** [comment]
I guess this library has the purpose of being applied to a human input interface ... and humans usually use "%" as percentage ... as I described, even Google or Wolfram Alpha, have the chance to use that notation. It was just an idea to simulate that feature. I undertand if you don't want to include in the library, I'll fork it with more human typical uses ;-)
